source( "mseRguiBatchFuns.r" )
source( "mseRguiSimFuns.r" )
source( "mseRguiViewFuns.r" )
source( "mseRguiOptFuns.r" )
source( "mseRguiPerfFuns.r" )
source( "mseRguiTrackFuns.r" )
source( "mseRguiHelperFuns.r" )
source( "mseRglobals.r" )
source( "mseRoptions.r" )
source( "mseRplots.r" )
source( "mseRstats.r" )
source( "mseRsystem.r" )
source( "mseRrefPoints.r" )
source( "mseRtools.r" )
source( "read.admb.R" )
require(ref)

compile("assessCA.cpp")
compile("assessDD.cpp")